### ISSUE TITLE
CPAN and MetaCPAN doesn't have the latest version

### ISSUE THREAD

**Issue by manwar** [toddr/IO-Tty#5]
Hi,

I noticed github has the latest v1.13_01. However CPAN and MetaCPAN still has v1.12
It would be nice if they also have the same version as the github, as not everyone look for updated code in github.

Many Thanks,

Best Regards,
Mohammad S Anwar

**Comment by toddr** [comment]
Thanks I totally missed this until just now. I'm working on a release.
